ログメッセージが二重に出力される問題の解決
fierte-product-development/Standard-Library-Extension pull request #10
Opened 2023-05-22 06:23 UTC by makoto-horinouchi

#9 の対応です。

## 改修内容
- Handlerにどのレベルのログまでを出力対象とするかを設定する `LevelFilter` クラスを実装
- `sys.stdout`のFilterを設定するために引数を整理
- テストの実装と修正

二重に出力されていないことを確認したログ
```
PS C:\SLE_Logger_Test> python main.py
    INFO 2023-05-22 15:21:20 [main] INFO
 WARNING 2023-05-22 15:21:20 [main] WARNING
   ERROR 2023-05-22 15:21:20 [main] ERROR (10:main)
CRITICAL 2023-05-22 15:21:20 [main] CRITICAL (11:main)
```

2023-05-22 06:24 UTC, makoto-horinouchi commented
@junkmd 1次レビューお願いします。

2023-05-22 06:45 UTC, junkmd requested changes
あと、`test_OutputStackTrace_ErrorRaised`で`capfd.readouterr`を使って標準出力、標準エラーの内容を確認しているように、`INFO`, `DEBUG`, `WARNING`, `CRITCAL`のケースでも標準出力、標準エラーの内容を確認するテストがあった方が良いと思いますがどうですか?

2023-05-22 06:45 UTC, junkmd commented on fmodules/logging_wrappers.py
> +    def __init__(self, max_level):
型ヒントをお願いします。

[`LogRecord.levelno`の型は`int`](https://github.com/python/typeshed/blob/35450d9c0d673fc713c3210d8c25d19425f9790e/stdlib/logging/__init__.pyi#LL386C6-L386C17)なので`max_level: int`のはずです。

2023-05-22 06:45 UTC, junkmd commented on fmodules/logging_wrappers.py
> +def _MakeHandler(handler: type[Handler], min_level=NOTSET, max_level=CRITICAL, **kwargs) -> Handler:
これも`min_level: int`、`max_level: int`で

2023-05-22 06:45 UTC, junkmd commented on fmodules/tests/test_logging_wrappers.py
> -        assert out.startswith(expected)
`out`では「何も出力されていない」ことを確認する=`out == ""`ならばいいと思います。

2023-05-24 08:17 UTC, yuhei-kishida approved these changes
OKです！ありがとうございます！

2023-05-24 08:26 UTC, merged