Streamに出力されるログレベルとファイルに出力されるログレベルを別々に設定
fierte-product-development/Standard-Library-Extension pull request #11
Opened 2023-07-05 01:00 UTC by makoto-horinouchi

#8 の対応です。

## 概要
- LOGGERが引数に依らず、`DEBUG`レベル以上のログを受け取るように改修
- Streamに出力するログレベルと、Fileに出力するログレベルを下記の通り変更
  - Stream: `INFO` ~ `CRITICAL`
  - File: `DEBUG` ~ `CRITICAL`

## 影響範囲
引数に依っては、下記の影響を受けます
- `Stream`に`DEBUG`レベルのログが流れないようになります
- `File`に`DEBUG`レベルのログが流れるようになります

2023-07-05 01:02 UTC, makoto-horinouchi commented
@yuhei-kishida 1次レビューお願いします。

2023-07-05 02:28 UTC, yuhei-kishida approved these changes
OKです！対応ありがとうございます！

2023-07-05 02:35 UTC, junkmd requested changes
プロダクションコードは申し分ないです!
ありがとうございます。

テストでDEBUGレベルの内容を検証できなくなっちゃったのが若干不安です。

ファイルに書き込まれる内容を`Path`や`sys`や`os`から捕まえるのは大変なので、[`caplog`フィクスチャの`record_tuples`](https://docs.pytest.org/en/7.1.x/how-to/logging.html#caplog-fixture)を使うことで「DEBUGレベルのログも握りつぶしているわけじゃなくてちゃんと(しかるべきレベルにハンドラを設定しているファイルには)出るよ」とテストするのはどうでしょうか?

2023-07-05 04:13 UTC, makoto-horinouchi commented
> ファイルに書き込まれる内容をPathやsysやosから捕まえるのは大変なので、(DEBUGレベルのテストだけでも)[caplogフィクスチャのrecord_tuples](https://docs.pytest.org/en/7.1.x/how-to/logging.html#caplog-fixture)を使うことで「DEBUGレベルのログも握りつぶしているわけじゃなくてちゃんと(しかるべきレベルにハンドラを設定しているファイルには)出るよ」とテストするのはどうでしょうか?

賛成です！上手くpytestの機能を使えばログファイルの中身を確認してテストが可能なので、そちらで実装してみます。

2023-07-05 04:25 UTC, junkmd requested changes

2023-07-05 04:25 UTC, junkmd commented on fmodules/tests/test_logging_wrappers.py
> +    def test_OutputDebugLog_TakesSpecificLevel(self, capfd):
テストする意味合いが変わったので、名前も変わると思います。

「ストリームにログを出力しない_debugメソッドを呼んだ場合」相当だと考えています。

2023-07-05 04:25 UTC, junkmd commented on fmodules/tests/test_logging_wrappers.py
> +        log_file = Path(tmp_path) / ".log" / f"{tmp_path.resolve().name}.log"
`tmp_path`はもう`Path`型だからキャスト不要だと思います。
IDE上で型ヒントを出したいなら`def test_...(..., tmp_path: Path, ...)`みたいに引数アノテーションする方が良いかと思います。

2023-07-05 04:25 UTC, junkmd commented on fmodules/tests/test_logging_wrappers.py
> +    def test_WriteDebugLog_TakesSpecificLevel(self, fixed_time, tmp_path):
こっちは「ファイルにログを出力する_debugメソッドを呼んだ場合」相当かと。

ひょっとして上のテストとこのテスト合わせて、「ログをストリームには出力しないけどファイルには出力する_debugメソッドを呼んだ場合」の方が包括的に見れる?

```py
    def test...(self, fixed_time, tmp_path: Path, capfd):
        getLogger(tmp_path, root=True)
        any_module.debug("test")
        out, err = capfd.readouterr()
        assert out == ""
        assert err == ""
        log_file = tmp_path / ".log" / f"{tmp_path.resolve().name}.log"
        assert log_file.read_text() == f"   DEBUG {fixed_time} [{Path(__file__).stem}.any_module] test (12:debug)\n"
```

2023-07-05 04:36 UTC, makoto-horinouchi commented on fmodules/tests/test_logging_wrappers.py
> +    def test_OutputDebugLog_TakesSpecificLevel(self, capfd):
上記を参考に、 「Test_DoesntOutputLogToStream_CalledDebugLogMethod」に変更します

2023-07-05 04:37 UTC, makoto-horinouchi commented on fmodules/tests/test_logging_wrappers.py
> +    def test_WriteDebugLog_TakesSpecificLevel(self, fixed_time, tmp_path):
1メソッド内のテスト観点が複数になって見通しが悪くなってしまうので、テスト条件が同じでもテストは分けるようにします。

2023-07-06 00:28 UTC, makoto-horinouchi commented
昨日のGitHubバグによりPRが画面上に反映されないのでcloseして立て直します
(ブランチには反映されているので問題ないと思いますが念のため)

2023-07-06 00:28 UTC, closed without merging