Add stack trace to
fierte-product-development/Standard-Library-Extension pull request #7
Opened 2022-01-20 09:01 UTC by junkmd

2022-01-20 09:25 UTC, hiro-torii commented
setup.cfgのバージョンも2.0.1にしましょうか

2022-01-20 09:49 UTC, hiro-torii requested changes
すみません、細かい所で少しだけあります。

2022-01-20 09:49 UTC, hiro-torii commented on fmodules/tests/test_logging_wrappers.py
> +def created_time(mocker) -> None:
時間を固定するのであれば，crated_timeよりもふさわしい命名がありそうに感じますがどうですか

2022-01-20 09:49 UTC, hiro-torii commented on fmodules/tests/test_logging_wrappers.py
> +        def test_OutputStackTrace_SInfoIsStr(self, fmt: fFormatter, created_time):
`SInfo`ってStackInfoですか？　そこまで略す必要は周りのテスト名と比べてもないように見えます。

2022-01-20 09:52 UTC, junkmd commented on fmodules/tests/test_logging_wrappers.py
> +        def test_OutputStackTrace_SInfoIsStr(self, fmt: fFormatter, created_time):
ここは素直に`StackInfo`に直します。

2022-01-20 09:56 UTC, junkmd commented on fmodules/tests/test_logging_wrappers.py
> +def created_time(mocker) -> None:
「固定された時間」を素直に訳して`fixed_time`が適切な気がしてきたのでそうします。

2022-01-20 09:59 UTC, junkmd commented
修正しました。

宜しくお願いします。

2022-01-21 01:51 UTC, hiro-torii approved these changes
対応ありがとうございます。

2022-01-21 01:52 UTC, hiro-torii commented
@yuhei-kishida 二次レビューお願いします。

2022-01-21 02:40 UTC, yuhei-kishida reviewed
1点理由の確認だけさせてください。

2022-01-21 02:40 UTC, yuhei-kishida commented on fmodules/tests/test_logging_wrappers.py
> +        assert out == f"    INFO {fixed_time} [{root_name}.any_module] test\n"
このアサーションの変更って時間をモックしたため、ログメッセージ厳密に比較する方針に変更したってことですか？

2022-01-21 02:53 UTC, junkmd commented on fmodules/tests/test_logging_wrappers.py
> +        assert out == f"    INFO {fixed_time} [{root_name}.any_module] test\n"
そうです。
カンバンの「その他の変更点」のところに記載しています。
(fixture名は変わってしまったため変更しました)

宜しくお願いします。

2022-01-21 02:56 UTC, yuhei-kishida approved these changes
対応ありがとうございます。

2022-01-21 03:01 UTC, merged